import {
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bot,
  Box,
  Calendar,
  Check,
  Compass,
  Download,
  FileText,
  Gem,
  Github,
  Globe,
  GraduationCap,
  HeartPulse,
  Headphones,
  Home,
  Image,
  Instagram,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Linkedin,
  Link2,
  Mail,
  MapPin,
  Phone,
  Menu,
  MessageCircle,
  Monitor,
  Moon,
  Play,
  RefreshCw,
  Rocket,
  Settings2,
  Share2,
  Sparkles,
  Star,
  Sun,
  Target,
  Trash2,
  Video,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  arrow: ArrowRight,
  up: ArrowUp,
  external: ArrowUpRight,
  bot: Bot,
  cube: Box,
  calendar: Calendar,
  check: Check,
  compass: Compass,
  download: Download,
  file: FileText,
  gem: Gem,
  github: Github,
  globe: Globe,
  graduation: GraduationCap,
  heart: HeartPulse,
  headset: Headphones,
  home: Home,
  image: Image,
  instagram: Instagram,
  layers: Layers,
  dashboard: LayoutDashboard,
  bulb: Lightbulb,
  linkedin: Linkedin,
  link: Link2,
  mail: Mail,
  phone: Phone,
  pin: MapPin,
  menu: Menu,
  chat: MessageCircle,
  monitor: Monitor,
  moon: Moon,
  play: Play,
  refresh: RefreshCw,
  rocket: Rocket,
  cog: Settings2,
  share: Share2,
  spark: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  trash: Trash2,
  video: Video,
  wrench: Wrench,
  close: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  className,
  strokeWidth = 2,
}: {
  name: IconName;
  className?: string;
  strokeWidth?: number;
}) {
  const Comp = icons[name];
  return <Comp className={className} strokeWidth={strokeWidth} aria-hidden />;
}
